### PR TITLE
Add item metrics for Memcached

### PR DESCRIPTION
**Pull request by gfediere**
- get items statistics by slabs ID

---
This change is [Reviewable](https://reviewable.io/reviews/criteo/mewpoke/6)

### CODE REVIEW

**Comment by erebe** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 39 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nFEO0NGHV6GDWkWju:-L0nFEO18SwdlrvpoolN:bseuukj) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L39)):*
> ```Java
>     static final Gauge STATSITEMS = Gauge.build()
>                                          .name("memcached_items")
>                                          .help("get stats items statistics by slabs ID")
> ```

typo slab instead of stats

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 67 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nFNMXrRfnuYtdqvf5:-L0nFNMXrRfnuYtdqvf6:bjcfmti) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L67)):*
> ```Java
>     {
>         nodesStats.forEach((addr, stats) -> {
>             stats.forEach((statname, statvalue) -> { //most of slabs are returned as: "items:2:free_chunks", need to split
> ```

what happens when we are not in the most of the time ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6)*

**Comment by erebe** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 103 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nHF4Tb5cmPIVm6W3e:-L0nHF4Tb5cmPIVm6W3f:b-aic81w) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L103)):*
> ```Java
>         LATENCY.clear();
>         STATS.clear();
>         STATSITEMS.clear();
> ```

SLABS_ITEMS_STATS maybe ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6)*

**Comment by vdemonchy** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 39 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nFEO0NGHV6GDWkWju:-L0nHCWl8-UKr344gCVR:b2m3ix0) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L39)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

typo slab instead of stats
</blockquote></details>

Should rather be "Get items statistics by slab ID"

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 103 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nHF4Tb5cmPIVm6W3e:-L0nHRCshKvSkuZqjbCc:b-hrw46o) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L103)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

SLABS_ITEMS_STATS maybe ?
</blockquote></details>

No because the memcached command is "stats items"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6)*

**Comment by vdemonchy** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6)*

**Comment by gfediere** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 39 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nFEO0NGHV6GDWkWju:-L0nPd0mvHsZrrxrTE-b:b32w0x) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L39)):*
<details><summary><i>Previously, vdemonchy (Victor Demonchy) wrote…</i></summary><blockquote>

Should rather be "Get items statistics by slab ID"
</blockquote></details>

OK

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 67 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nFNMXrRfnuYtdqvf5:-L0nO_WtbelDPUP5RciI:b-yduwec) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L67)):*
<details><summary><i>Previously, erebe (Erèbe - Romain Gerard) wrote…</i></summary><blockquote>

what happens when we are not in the most of the time ?
</blockquote></details>

forgot to delete this comment, not needed anymore

---

*[src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java, line 103 at r1](https://reviewable.io:443/reviews/criteo/mewpoke/6#-L0nHF4Tb5cmPIVm6W3e:-L0nOhzdlDAheMR8LpYJ:bsg6ccg) ([raw file](https://github.com/criteo/mewpoke/blob/0c5aac49a440c8ceaed1881016b4d2b368a002c6/src/main/java/com/criteo/nosql/mewpoke/memcached/MemcachedMetrics.java#L103)):*
<details><summary><i>Previously, vdemonchy (Victor Demonchy) wrote…</i></summary><blockquote>

No because the memcached command is "stats items"
</blockquote></details>

 Agree with @vdemonchy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6)*

**Comment by erebe** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6#-:-L0nRqGe4xRjG_auo355:bnfp4nl)*

**Comment by vdemonchy** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6#-:-L0nVfJadbZyynK-hnj4:bnfp4nl)*

**Comment by vdemonchy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/criteo/mewpoke/6)*

**Pull request merged**
